defaults:
    - agent: sac

env: cheetah_run

# this needs to be specified manually
experiment: test_exp

num_train_steps: 1e6
save_steps: 50000
time_to_run: 83880 # about 11:45 hours
resume: true
replay_buffer_capacity: ${num_train_steps}
base_lr: 1e-3
init_alpha: 0.1
decay_step_size: 1e5
decay_factor: 0.50
reward_scale: 10.0

num_seed_steps: 5000

eval_frequency: 200000
num_eval_episodes: 10

device: cuda

# logger
log_frequency: 5000
log_save_tb: true

# video recorder
save_video: true
frame_height: 540

seed: 1

# GNN parameters
gnn_parameters:
    conv_type: node # [node, edge, attention]
    input_batch_norm: false
    hidden_dim: 128
    ignore_neighbors: false
    ignore_neighbors_at_testing: false
    hidden_depth: 2

# turbulence options
only_do_turb_control: false
use_turbulence_control: true
turbulence_model: NS    #[NS, null, constant, circular]
sim_dim: 2
turbulence_base_folder: /mnt/beegfs/data/diego/turbulence/
use_ns_regularization: false
ns_regularization_weight: 1.0
measurement_noise: true
use_wind_pressure_sensors: false

# wind sensor parameters
wind_sensor:
    max_speed: 60.0 # m/s
    speed_accuracy: 1.2 # m/s
    angle_accuracy: 3.0 # degrees

RL_parameters:
    use_error_mag_reward: true
    error_mag_reward_weight: 1.0
    use_cosine_reward: false
    cosine_reward_weight: 5.0
    use_action_mag_reward: true
    action_mag_reward_weight: 0.0001 #0.01

# Formation params
formation_params:
    init_points: in_formation               # [random, in_formation]
    formation_contro_type: simple           # [simple, magnus]
    num_nodes: 3
    #   [
    #       0 -> "small triangle, nodes=3",
    #       1 -> "Triangle, nodes=21",
    #       2 -> "grid 2x2"
    #       3 -> "grid 3x3"
    #       4 -> "grid 4x4"
    #       5 -> "grid 5x5"
    #       6 -> "Platoon", 3 -> "grid 3x3",
    #   ]
    formation_type: 0
    graph_type: 'formation'                 # [formation, complete, knn]

# hydra configuration
hydra:
    name: ${env}
    run:
        dir: ./output/${now:%Y.%m.%d}/${now:%H%M}_${agent.name}_${experiment}_disc_${agent.params.discount}
