defaults:
    - agent: sac

env: cheetah_run

# this needs to be specified manually
experiment: test_exp

num_train_steps: 1e7
replay_buffer_capacity: ${num_train_steps}

num_seed_steps: 5000

eval_frequency: 10000
num_eval_episodes: 5

device: cuda

# logger
log_frequency: 10000
log_save_tb: true

# video recorder
save_video: true

seed: 1

# GNN parameters
gnn_parameters:
    conv_type: node # [node, edge]
    input_batch_norm: false

# turbulence options
only_do_turb_control: false
use_turbulence_control: true
turbulence_model: constant    #[NS, null, constant, circular]
sim_dim: 2
turbulence_base_folder: /mnt/beegfs/data/diego/turbulence/
use_ns_regularization: false
ns_regularization_weight: 1.0

# Formation params
formation_params:
    formation_contro_type: simple   # [simple, magnus]
    num_nodes: 3
    formation_type: 0   #   [0-> "small triangle, nodes=3", 1 -> "Triangle, nodes=21", 2 -> "Platoon", 3 -> "grid 3x3", 4 -> "grid 4x4"]

# hydra configuration
hydra:
    name: ${env}
    run:
        dir: ./output/${now:%Y.%m.%d}/${now:%H%M}_${agent.name}_${experiment}_disc_${agent.params.discount}
