agent:
  name: sac
  class: gcnn_agents.GCNNSACAgent
  params:
    num_nodes: ${formation_params.num_nodes}
    use_ns_regularization: ${use_ns_regularization}
    ns_regularization_weight: ${ns_regularization_weight}
    obs_dim: ??? # to be specified later
    action_dim: ??? # to be specified later
    action_range: ??? # to be specified later
    device: ${device}
    critic_cfg: ${double_q_critic}
    actor_cfg: ${diag_gaussian_actor}
    discount: 0.95
    init_temperature: ${init_alpha}
    alpha_lr: ${base_lr}
    alpha_betas: [0.9, 0.999]
    actor_lr: ${base_lr}
    actor_betas: [0.9, 0.999]
    actor_update_frequency: 1
    critic_lr: ${base_lr}
    critic_betas: [0.9, 0.999]
    critic_tau: 0.005
    critic_target_update_frequency: 2
    batch_size: 512
    learnable_temperature: false
    decay_step_size: ${decay_step_size}
    decay_factor: ${decay_factor}
    
double_q_critic:
  class: gcnn_agents.GCNNDoubleQCritic
  params:
    num_nodes: ${formation_params.num_nodes}
    formation_type: ${formation_params.formation_type}
    conv_type: ${gnn_parameters.conv_type}
    input_batch_norm: ${gnn_parameters.input_batch_norm}
    obs_dim: ${agent.params.obs_dim}
    action_dim: ${agent.params.action_dim}
    hidden_dim: ${gnn_parameters.hidden_dim}
    hidden_depth: 2
    ignore_neighbors: ${gnn_parameters.ignore_neighbors}
    graph_type: ${formation_params.graph_type}
    
diag_gaussian_actor:
  class: gcnn_agents.GCNNDiagGaussianActor
  params:
    num_nodes: ${formation_params.num_nodes}
    formation_type: ${formation_params.formation_type}
    use_ns_regularization: ${use_ns_regularization}
    conv_type: ${gnn_parameters.conv_type}
    input_batch_norm: ${gnn_parameters.input_batch_norm}
    obs_dim: ${agent.params.obs_dim}
    action_dim: ${agent.params.action_dim}
    hidden_depth: 2
    hidden_dim: ${gnn_parameters.hidden_dim}
    log_std_bounds: [-5.0, 5.0] #[-0.2, 0.2]
    ignore_neighbors: ${gnn_parameters.ignore_neighbors}
    graph_type: ${formation_params.graph_type}
